2025-03-05 00:08:32,618 INFO    MainThread:568 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 00:08:32,618 INFO    MainThread:568 [wandb_setup.py:_flush():67] Configure stats pid to 568
2025-03-05 00:08:32,618 INFO    MainThread:568 [wandb_setup.py:_flush():67] Loading settings from C:\Users\-PC-\.config\wandb\settings
2025-03-05 00:08:32,618 INFO    MainThread:568 [wandb_setup.py:_flush():67] Loading settings from D:\Programms\Programming\PythonProjects\text-to-motion\wandb\settings
2025-03-05 00:08:32,618 INFO    MainThread:568 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 00:08:32,618 INFO    MainThread:568 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./log\t2m\Comp_v6_KLD04\wandb\run-20250305_000832-zs7486vu\logs\debug.log
2025-03-05 00:08:32,619 INFO    MainThread:568 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./log\t2m\Comp_v6_KLD04\wandb\run-20250305_000832-zs7486vu\logs\debug-internal.log
2025-03-05 00:08:32,619 INFO    MainThread:568 [wandb_init.py:init():761] calling init triggers
2025-03-05 00:08:32,619 INFO    MainThread:568 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 00:08:32,619 INFO    MainThread:568 [wandb_init.py:init():784] starting backend
2025-03-05 00:08:32,619 INFO    MainThread:568 [wandb_init.py:init():788] sending inform_init request
2025-03-05 00:08:32,736 INFO    MainThread:568 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-05 00:08:32,737 INFO    MainThread:568 [wandb_init.py:init():803] backend started and connected
2025-03-05 00:08:32,738 INFO    MainThread:568 [wandb_init.py:init():896] updated telemetry
2025-03-05 00:08:32,873 INFO    MainThread:568 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 00:08:33,806 INFO    MainThread:568 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 00:08:37,682 INFO    MainThread:568 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 00:08:37,682 INFO    MainThread:568 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 00:08:37,682 INFO    MainThread:568 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 00:08:37,682 INFO    MainThread:568 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 00:08:37,720 INFO    MainThread:568 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 00:20:16,388 WARNING MsgRouterThr:568 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "D:\Programms\Programming\PythonProjects\text-to-motion\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 258, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programms\Programming\PythonProjects\text-to-motion\.venv\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programms\Programming\PythonProjects\text-to-motion\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programms\Programming\PythonProjects\text-to-motion\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 262, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programms\Programming\PythonProjects\text-to-motion\.venv\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "D:\Programms\Programming\PythonProjects\text-to-motion\.venv\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 00:20:17,209 INFO    MsgRouterThr:568 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
